# Site settings
title: Mikhail Adamenko
email: mikhail.adamenko@protonmail.com
description: >-
  Learn various frameworks, programming languages in easy and fun way.
baseurl: ""
url: "https://mikhailadamenko.design/"
github_username:  A-Mikhail
disqus:
  shortname: mikhailadamenko
rss: rss
collections:
  lua:
    output: true
  love:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed