# Site settings
title: Mikhail Adamenko
email: mikhail.adamenko@protonmail.com
description: >-
  Tutorials of different frameworks, technologies in both Russian and English languages.
baseurl: ""
url: "http://mikhailadamenko.design/"
github_username:  A-Mikhail
disqus:
  shortname: mikhailadamenko
rss: rss

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed